### PR TITLE
Solved the 'too many values to unpack' bug in module

### PR DESCRIPTION
**Pull request by Rishaw-Developer**
### Error
dev2

### Solution
dev3

### CODE REVIEW

**Comment by se1exin** [comment]
I hit the same issue with the example code for the Hand Tracking example, but I think perhaps the documentation needs to be updated instead - so as to detail the required/expected input to the `findDistance` function, which is causing the bug.

Here is an example from the working source that correctly inputs into the `findDistance` function: https://github.com/cvzone/cvzone/blob/master/cvzone/HandTrackingModule.py#L189

I think the documentation and example code should probably be updated to reflect this instead of changing the module behaviour

**Comment by iseahound** [comment]
In case any noobs like myself are confused about the hand tracking example, 

The line:

            length, info, img = detector.findDistance(lmList1[8], lmList2[8], img)  # with draw

should be changed to

            length, info, img = detector.findDistance(lmList1[8][0:2], lmList2[8][0:2], img)  # with draw

as per [se1exin](https://github.com/se1exin)'s suggestion.

**Comment by Rishaw-Developer** [comment]
Thanks for the help. It's really helpful.

**Comment by iverdugos** [comment]
Thanks very much, this solved my problem with one of Murtaza's awesome tutorials: 
https://www.youtube.com/watch?v=3xfOa4yeOb0

**Pull request closed without merging**
